#!/bin/sh

SITE_DIR="/home/forge/$1"

mkdir -p $SITE_DIR

cd $SITE_DIR

mkdir tmp

cd tmp

wget https://ghost.org/zip/ghost-latest.zip --no-check-certificate

unzip -d .. ghost-latest.zip

cd ..

rm -rf tmp

npm install --production
